### ISSUE TITLE
How to access $stateParams from component

### ISSUE THREAD

**Issue by matejkramny** [ui-router/angular-hybrid#36]
Thanks for your efforts on making this available.

How can the (ng2+) component access the `$stateParams` service and `$rootScope` potentially?

I tried importing `StateParams` from `@uirouter/angular` but it seems like that module is not available because angular complains.

**Comment by christopherthielen** [comment]
If it's a routed component, it's best to inject the `Transition` and get `transition.params()`.  

```js
constructor(trans: Transition) {
  const params = trans.params();
}
```

Otherwise you can inject `UIRouterGlobals` and access `UIRouterGlobals.params`.  Globals aren't updated until _after a transition has completed successfully_.

```js
constructor(globals: UIRouterGlobals) {
  const params = globals.params;
}
```

To get the `$rootScope` you will need to make the AngularJS service available to Angular, as described here: https://angular.io/docs/ts/latest/guide/upgrade.html#!#making-angularjs-dependencies-injectable-to-angular

The easiest way is to inject the AngularJS injector and get it from there:

```js
constructor(@Inject('$injector') $injector) {
  const $rootScope = $injector.get('$rootScope');
}
```

**Comment by matejkramny** [comment]
Works, many thanks!
