### ISSUE TITLE
After update to 15: UI router error TypeError: this.factory is undefined

### ISSUE THREAD

**Issue by hheexx** [ui-router/angular-hybrid#585]
We were already on Angular 15 with angular-hybrid version 14 working fine.

Today I updated to angular-hybrid 15 and site wont load under ng serve with following error:

![image](https://user-images.githubusercontent.com/103767/226908752-e74956a0-8d57-4f7c-8e48-4261027bcd9b.png)

production build looks fine btw

**Comment by wawyed** [comment]
Can you double check you are using @uirouter/angular-hybrid@15.0.1?

**Comment by wawyed** [comment]
Also what do you mean production build looks fine?

**Comment by hheexx** [comment]
Call stack does not help at all?

**Comment by wawyed** [comment]
Not really, sorry

**Comment by pacome35220** [comment]
Same problem for me with v15.0.1, I can give you a more precise stacktrace :

I don't use `ng build` or `ng serve`, I use a custom webpack config.

PS : is it possible to [update your exemple of custom webpack config](https://github.com/ui-router/sample-app-angular-hybrid/tree/custom-webpack-config) to Angular 15 ?

![image](https://user-images.githubusercontent.com/33552035/228575767-6ebe4e55-a797-4362-b142-91f169e659d9.png)
![image](https://user-images.githubusercontent.com/33552035/228577066-9ef8f454-bcf1-43dd-8e8c-e2fbdd1eb01c.png)

Thank you for your time.

**Comment by wawyed** [comment]
Hi, the example projects were failing without it. Is the way you bootstrap the app different from the example project? https://github.com/ui-router/sample-app-angular-hybrid

**Comment by xfh** [comment]
I have the same problem with an Angular 15 hybride app. Indeed, downgrading to version 14 works.

I think I found the problem - at least I could reproduce in the sample-app-angular-hybrid.

`@uirouter/angularjs` pulls in `@uirouter/core@6.0.8` - core should be on version 6.1.0.

In my app, this causes a typescript compilation error, due to conflicting uirouter/core types.
To resolve the conflict, I've added the following override to my package.json (npm uses `overrides`, yarn uses `resolutions`):
```
  "overrides": {
    "@uirouter/core": "6.1.0"
  },
  "resolutions": {
    "@uirouter/core": "6.1.0"
  }
```

Adding the override to the sampe-app-angular-hybrid repo causes the runtime error as reported in this issue.

### Conclusion:
- The update in angular-hybrid should be reverted because we cannot use two different uirouter/core dependencies at runtime
- @uirouter/angularjs should be updated to allow `@uirouter/core@6.1.0` dependencies

### Current workaround:
- Use overrides to get uirouter/core version 6.1.0
- Use angular-hybrid version 14

**Comment by pacome35220** [comment]
@xfh I want to use Angular v15 and downgrading ui-router to version v14 is not possible for me because I'm using npm v8, and `npm install` fails because the resolution of the dependency tree is stricter with npm v8, so I get an error during `npm install`.

![image](https://user-images.githubusercontent.com/33552035/229525702-418a6ee5-2c5b-48a1-b684-7397ec62fcf4.png)

**Comment by xfh** [comment]
Ultimately, you are depending on `@uirouter/angularjs@1.0.30` - otherwise you wouldn't need angular-hybrid.

`@uirouter/angularjs` hasn't been maintained since 2 years. It still depends on `@uirouter/core 6.0.8`. I'd be very surprised if you didn't have these dependency conflicts before. Even with uirouter/angular-hybrid 15, you will have a dependency conflict due to uirouter/angularjs. It has nothing to do with npm v8.

In the absence of a new release, all you can do is to ignore the well-meant advise of npm and enforce the package installation - hoping that there is no API incompatibility. uirouter/angularjs is the reason I've allowed legacy-peer-deps.

**Comment by wawyed** [comment]
I'll try to change ui-router/angularjs to use peerDependencies for uirouter/core when I get some free time. Would that solve the issues you've been having?

**Comment by pacome35220** [comment]
Unfortunately I don't want to allow legacy-peer-deps using `--force` or `--locagy-peer-deps` in my CI/CD pipeline because it might cause other problems later for others packages.

I had no dependency conflicts before because @uirouter/core was in 6.0.8 in all @uirouter packages.

The solution I found is a to update subdependencies `npm update @uirouter/core` to 6.1.0.

- `@uirouter/angularjs@1.0.30` -> @uirouter/core 6.0.8
- `@uirouter/angular@11.0.0` -> @uirouter/core 6.1.0

![image](https://user-images.githubusercontent.com/33552035/229736082-92d95ed4-6080-47fe-ac07-ee5e09d31684.png)

Now there are 2 versions of @uirouter/core :
- 6.0.8 from @uirouter/angularjs
- 6.1.0 from @uirouter/angular

and it works.

It's maybe not related to this issue but in my project but :

- I have to import Transition from @uirouter/angularjs instead of @uirouter/angular in my Angular routing module

**Comment by xfh** [comment]
> I'll try to change ui-router/angularjs to use peerDependencies for uirouter/core when I get some free time. Would that solve the issues you've been having?

Hi @wawyed, allowing 6.X peer dependencies in angularjs should fix the dependency conflicts, thanks!
You will also have to revert your change for angular-hybrid 15 well though - you will get the same problem as the original poster.

@pacome35220, do you really want to bundle two versions of urouter/core? That sounds to me way more fragile... Are you sure both routers are use the same configuration? It might not be a problem in a simple app, but if you configure for instance the [UrlConfig](https://ui-router.github.io/core/docs/latest/classes/_url_urlconfig_.urlconfig.html) to e.g. use a custom ParamTypeDefinition, you'd have to do so for each router...

You can easily verify in the sample app, that there are two uirouter/core dependencies bundled:
```
npm run build -- --source-map
npx source-map-explorer dist/**.js
```
![image](https://user-images.githubusercontent.com/9366771/229763425-d6e61a79-50b6-4f81-8fb5-e4019a89392e.png)

**Comment by wawyed** [comment]
Alright version 15.0.2 has been released. Please make sure you use either in your package.json:

if you use yarn:


```
  "resolutions": {
    "@uirouter/core": "^6.1.0"
  },
```

If you use npm:

```
  "overrides": {
    "@uirouter/core": "6.1.0"
  },
  ```
  
  This should solve the issues for now. I need to get access to uirouter/angularjs before I can fix the peerDep so for now this is the way to get it to work.

**Comment by wawyed** [comment]
No worries. Sorry I didn't realise the issue with the dependency that lead to the wrong fix.
